apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: demo-blog
data:
  BLOG_TITLE: "Blog of Naveen"
  BLOG_SUBTITLE: "Explore GitOps with Argo CD"
  AUTHOR: "Naveen"
  VERSION: "1.0.0"
  THEME: "dark"